### ISSUE TITLE
change def _set_facility_filter to address other geographies

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO_modules#15]
I think we need to update this function in DataSet.py to handle watersheds

**Comment by shansen5** [comment]
Yes.  Looks like an easy one to add.

**Comment by shansen5** [comment]
The function doesn't need to be changed.  It will handle it, using the region_field structure from geographies.py.  There, region_field['Watershed']['field'] is 'FAC_DERIVED_HUC', so it will add to the filter: 'FAC_DERIVED_HUC' = <HUC-code>, as expected.

        filter = '"' + region_field[region_type]['field'] + '"'
        if ( region_type == 'County' ):
            filter += ' like \'' + str( region_value ) + '%\''
        else:
            filter += ' = \'' + str( region_value ) + '\''
