### ISSUE TITLE
Move utilities.py from ECHO-Cross-Program distro to ECHO_modules

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO_modules#17]
Notebooks are having to clone ECHO-Cross-Program in order to get some utilities.py methods.  That results in their getting all of the .ipynb from ECHO-Cross-Program as well.
If utilities.py grows we could start to split it into more specialized groupings of functions.

**Comment by ericnost** [comment]
I really like this idea. If we did it right, it could be a part of modularizing these tools as a package (as @Mr0grog suggested), which would give them wider applicability.

The one thing I wonder about is whether ECHO-Cross-Program/utilities.py would have some unique features for that set of notebooks relative to other utilities.py files, such as in ECHO-COVID19 or ECHO-Watershed. I kind of doubt it. Even if that were the case, we could allow specific parameters to be adjusted.
