### ISSUE TITLE
Add Case Enforcements as a DataSet object

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO_modules#18]
We should consider adding some of the tables described here, especially CASE ENFORCEMENTS, as a DataSet object for users to select when looking at program data.

https://echo.epa.gov/tools/data-downloads/icis-fec-download-summary

We had this in before but I think we were interpreting it incorrectly.

My understanding is that these tables sometimes duplicate, but also sometimes adds new information about enforcement actions taken by the US EPA rather than state agencies.

We already have ICIC FEC EPA INSPECTIONS

See some of the discussion here: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/96#issuecomment-772005306

**Comment by ericnost** [comment]
This will be challenging because it involves two queries: one to associate facility IDs with enforcement action IDs and then another to pull up details of those enforcement actiosn

**Comment by shansen5** [comment]
We can use a linking table the same way we use EXP_PGM to link the facility IDs (ECHO EXPORTER) with program IDs (SDWA_IDS, RCRA_IDS,NPDES_IDS,AIR_IDS).  There are several data sets associated with CASE ENFORCEMENTS.  Do we need any others, or can we just start with CASE_ENFORCEMENTS?
CASE_DEFENDANTS.csv
CASE_ENFORCEMENT_CONCLUSION_COMPLYING_ACTIONS.csv
CASE_ENFORCEMENT_CONCLUSION_DOLLARS.csv
CASE_ENFORCEMENT_CONCLUSION_FACILITIES.csv
CASE_ENFORCEMENT_CONCLUSION_POLLUTANTS.csv
CASE_ENFORCEMENT_CONCLUSIONS.csv
CASE_ENFORCEMENT_CONCLUSION_SEP.csv
CASE_ENFORCEMENTS.csv
CASE_ENFORCEMENT_TYPE.csv
CASE_FACILITIES.csv
CASE_LAW_SECTIONS.csv
CASE_MILESTONES.csv
CASE_PENALTIES.csv
CASE_POLLUTANTS.csv
CASE_PRIORITIES.csv
CASE_PROGRAMS.csv
CASE_REGIONAL_DOCKETS.csv
CASE_RELATED_ACTIVITIES.csv
CASE_RELIEF_SOUGHT.csv
CASE_VIOLATIONS.csv

**Comment by ericnost** [comment]
@shansen5 Good question! I think let's just start with CASE ENFORCEMENTS and CASE PENALTIES so that we can build as full a picture as possible of the US EPA enforcement actions that aren't already recorded in the program-specific tables.

**Comment by shansen5** [comment]
I added a few of the others to my request of Stonybrook.  They seemed to me likely to be used.
