### ISSUE TITLE
Add NPDES_EFF_VIOLATIONS as a DataSet object

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO_modules#20]
This data table usefully summarizes effluent violations of the Clean Water Act. It doesn't give us total discharges like DMRS_FY2020 does, but it does give us exceedences and other violations for a longer historical record

```
"Effluent Violations": dict(
        echo_type="NPDES",
        base_table="NPDES_EFF_VIOLATIONS",
        table_name="NPDES_EFF_VIOLATIONS_MVIEW",  # does not exist yet!
        idx_field="NPDES_ID",
        date_field="MONITORING_PERIOD_END_DATE",
        date_format="%m/%d/%Y", 
        agg_type="count", 
        agg_col="EXCEEDENCE_PCT",  
        unit="violations"
    ),
```

**Comment by shansen5** [comment]
Can we predict which fields we will use, to reduce the size and complexity of the data set?


Element Name | Data Type | Length
-- | -- | --
NPDES_ID1 | Char | 9
VERSION_NMBR | Num | 22
ACTIVITY_ID | Num | 22
NPDES_VIOLATION_ID3 | Num | 22
PERM_FEATURE_NMBR | Char | 4
PERMIT_ACTIVITY_ID | Num | 22
LIMIT_SET_DESIGNATOR | Char | 2
MONITORING_LOCATION_CODE | Char | 3
DMR_FORM_VALUE_ID | Num | 22
DMR_VALUE_NMBR | Num | 22
DMR_VALUE_ID | Num | 22
DMR_PARAMETER_ID | Num | 22
NODI_CODE | Char | 3
ADJUSTED_DMR_VALUE_NMBR | Num | 22
VIOLATION_TYPE_CODE | Char | 6
VIOLATION_TYPE_DESC | Char | 100
VIOLATION_CODE | Char | 5
VIOLATION_DESC | Char | 100
PARAMETER_CODE | Char | 5
PARAMETER_DESC | Char | 100
MONITORING_PERIOD_END_DATE | Date | 7
NMBR_OF_REPORT | Num | 2
EXCEEDANCE_PCT | Num | 22
VALUE_QUALIFIER_CODE | Char | 3
UNIT_CODE | Char | 2
VALUE_RECEIVED_DATE | Date | 7
DAYS_LATE | Num | 22
ADJUSTED_DMR_STANDARD_UNITS | Num | 22
LIMIT_ID | Num | 22
DMR_VALUE_STANDARD_UNITS | Num | 22
VALUE_TYPE_CODE | Char | 3
RNC_DETECTION_CODE | Char | 3
RNC_DETECTION_DESC | Char | 100
RNC_DETECTION_DATE | Date | 7
RNC_RESOLUTION_CODE | Char | 3
RNC_RESOLUTION_DESC | Char | 100
RNC_RESOLUTION_DATE | Date | 7
STATISTICAL_BASE_CODE | Char | 3
STATISTICAL_BASE_MONTHLY_AVG | Char | 1

**Comment by ericnost** [comment]
Thank you for taking a look at this @shansen5!!! I think we can predict which columns we'd be most likely to use, in fact, since @emfreeman was working with more or less this same dataset.

I created this notebook a few weeks ago to try to check the numbers she was coming up with: https://colab.research.google.com/drive/1Kdc6vzgWywesDI-u9RS8rAdex6tr3y79#scrollTo=_FrDjTuZayCy

The notebook pulls from the NPDES_EFF_VIOLATIONS table in order to summarize the kinds of violations, pollutants, etc.

I took a look, and I see the following columns in use:

NPDES_ID
MONITORING_PERIOD_END_DATE = date field
RNC_DETECTION_CODE = the type of non-compliance (using this field currently to check whether the non-compliance is due to missing data)
RNC_RESOLUTION_CODE = whether or not the missing data has been resolved
VIOLATION_CODE = another indication of the type of non-compliance (could use VIOLATION_DESC instead since that will be easier to report)
EXCEEDENCE_PCT = how much the pollutant was discharged over the limit (percent) (this would be the `agg_field` I think)
PARAMETER_DESC = tells us the name of the pollutant
DMR_VALUE_NMBR = the actual amount discharged
DMR_VALUE_STANDARD_UNITS = the units of measurement for the effluent discharage
