### ISSUE TITLE
upload to pypi as package

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO_modules#49]
- [x] clean up repo (e.g. #48, remove extra files)
- [ ] create pypi account and add package
- [ ] edit notebooks to use `!pip install echo_modules` instead of `!pip install git+...`

**Comment by shansen5** [comment]
This file should be deleted. It was a possible alternative way to build the package. [pyproject.toml.setuptools](https://github.com/edgi-govdata-archiving/ECHO_modules/blob/main/pyproject.toml.setuptools)
